#!/usr/bin/env node
'use strict';

/**
 * generate-stubs.js
 *
 * Generates src/steps/_mcp-stubs.steps.ts — a temporary Cucumber step-def file
 * where every undefined step is replaced with a "pause stub" that:
 *   1. Writes a pause signal to mcp-bridge/<runId>/step-N-pause.json
 *   2. Waits for Claude to write mcp-bridge/<runId>/step-N-impl.js via MCP analysis
 *   3. Dynamically requires and executes the impl, retrying on failure
 *   4. Coalesces repeated Cucumber expressions into one binding and routes
 *      them by occurrence order, avoiding ambiguous step definitions
 *
 * Usage:
 *   node generate-stubs.js <output-file> '<steps-json>' [--world-import <path>] [--world-type <name>]
 *
 * steps-json: JSON array of { type, text, index }
 *   type  — "Given" | "When" | "Then"
 *   text  — step text with Cucumber expressions, e.g. "I click {string} button"
 *   index — sequential integer starting from 1
 *
 * Example:
 *   node generate-stubs.js src/steps/_mcp-stubs.steps.ts \
 *     '[{"type":"When","text":"I click on the {string} dropdown","index":1}]'
 */

const fs = require('fs');
const path = require('path');
const { readProjectProfile } = require('./fs-utils');

function parseArgs(argv) {
  const profile = readProjectProfile();
  const parsed = {
    outputFile: null,
    stepsJson: null,
    worldImport: profile?.world?.import_from_stub || '../support/world',
    worldType: profile?.world?.type || 'ScenarioWorld',
    pageUrlExpression: profile?.page_url_expression || "(world as any).page?.url?.()",
  };

  const positional = [];
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--world-import') {
      parsed.worldImport = argv[i + 1];
      i += 1;
      continue;
    }
    if (arg === '--world-type') {
      parsed.worldType = argv[i + 1];
      i += 1;
      continue;
    }
    positional.push(arg);
  }

  [parsed.outputFile, parsed.stepsJson] = positional;
  return parsed;
}

function toPosixPath(filePath) {
  return filePath.replace(/\\/g, '/');
}

function escapeForSingleQuotedImport(importPath) {
  return importPath.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const options = parseArgs(process.argv.slice(2));
const { outputFile, stepsJson, pageUrlExpression } = options;

if (!outputFile || !stepsJson) {
  console.error('Usage: node generate-stubs.js <output-file> <steps-json> [--world-import <path>] [--world-type <name>]');
  process.exit(1);
}

let steps;
try {
  steps = JSON.parse(stepsJson);
} catch (e) {
  console.error('Invalid JSON for steps:', e.message);
  process.exit(1);
}

if (!Array.isArray(steps) || steps.length === 0) {
  console.error('steps-json must be a non-empty array.');
  process.exit(1);
}

const VALID_TYPES = new Set(['Given', 'When', 'Then']);
for (let i = 0; i < steps.length; i++) {
  const s = steps[i];
  const errors = [];
  if (!VALID_TYPES.has(s.type)) errors.push(`type must be Given/When/Then, got "${s.type}"`);
  if (typeof s.text !== 'string' || s.text.length === 0) errors.push('text must be a non-empty string');
  if (!Number.isInteger(s.index) || s.index <= 0) errors.push(`index must be a positive integer, got ${s.index}`);
  if (errors.length > 0) {
    console.error(`Invalid step at position ${i}: ${errors.join('; ')}`);
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Parameter detection
// Map Cucumber expression tokens to TypeScript types and param names
// ---------------------------------------------------------------------------
const CUCUMBER_TYPES = {
  string: 'string',
  int: 'number',
  float: 'number',
  word: 'string',
  '': 'string', // bare {}
};

function getParams(stepText) {
  const params = [];
  const regex = /\{(string|int|float|word|)\}/g;
  let match;
  let i = 0;
  while ((match = regex.exec(stepText)) !== null) {
    const token = match[1];
    const tsType = CUCUMBER_TYPES[token] ?? 'string';
    params.push({ name: `param${i}`, tsType });
    i++;
  }
  return params;
}

// ---------------------------------------------------------------------------
// Header — imports + shared runtime
// ---------------------------------------------------------------------------
const outputCommentPath = toPosixPath(path.relative(process.cwd(), path.resolve(outputFile)) || outputFile);
const worldImportPath = escapeForSingleQuotedImport(options.worldImport);
const worldType = options.worldType;
const header = `// ${outputCommentPath}
// AUTO-GENERATED by mcp-step-implementor skill — DO NOT EDIT MANUALLY
// Delete this file once all steps have been finalised into real PO/step-def files.
import { Given, When, Then, setDefaultTimeout, BeforeAll } from '@cucumber/cucumber';
import { ${worldType} } from '${worldImportPath}';
import * as fs from 'fs';
import * as path from 'path';

const BRIDGE_ROOT = path.resolve(
  process.cwd(),
  process.env.MCP_STEP_BRIDGE_ROOT || 'mcp-bridge'
);
const RUN_ID = process.env.MCP_STEP_RUN_ID || 'default-run';
const BRIDGE = path.join(BRIDGE_ROOT, RUN_ID);
const RUN_STARTED_AT = Date.now();
// start-run.js is the single source of truth for timeout budgeting.
// The fallback only applies if the stubs are executed outside that launcher.
const RUN_TIMEOUT_MS = Number(
  process.env.MCP_STEP_RUN_TIMEOUT_MS ||
  process.env.MCP_STEP_TIMEOUT_MS ||
  600_000
);
const RUN_DEADLINE_AT = RUN_STARTED_AT + RUN_TIMEOUT_MS;
const IMPL_ATTEMPT_TIMEOUT_MS = Number(process.env.MCP_STEP_IMPL_TIMEOUT_MS || 60_000);

setDefaultTimeout(RUN_TIMEOUT_MS);

function readJsonIfExists(filePath: string): Record<string, unknown> {
  if (!fs.existsSync(filePath)) return {};
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
  } catch (error) {
    return {};
  }
}

/**
 * Atomic file write — prevents readers from seeing partially-written content.
 * Writes to a tmp file in the same directory, then renames (atomic on POSIX
 * when source and target are on the same filesystem).
 */
function atomicWriteFileSync(targetPath: string, content: string): void {
  const tmpPath = path.join(
    path.dirname(targetPath),
    \`.tmp.\${process.pid}.\${Date.now()}.\${path.basename(targetPath)}\`
  );
  fs.writeFileSync(tmpPath, content, 'utf8');
  fs.renameSync(tmpPath, targetPath);
}

function atomicWriteJsonSync(targetPath: string, value: unknown): void {
  atomicWriteFileSync(targetPath, JSON.stringify(value, null, 2));
}

function clearBridgeProtocolFiles(): void {
  if (!fs.existsSync(BRIDGE)) return;
  for (const entry of fs.readdirSync(BRIDGE)) {
    if (entry === 'launch.json') continue;
    if (/^step-\\d+-impl\\.js$/.test(entry)) continue;
    fs.rmSync(path.join(BRIDGE, entry), { recursive: true, force: true });
  }
}

BeforeAll(function () {
  fs.mkdirSync(BRIDGE_ROOT, { recursive: true });
  fs.mkdirSync(BRIDGE, { recursive: true });
  clearBridgeProtocolFiles();
  stepOccurrences.clear();
  // Diagnostic: log which impl files survived the cleanup
  const survivingImpls = fs.readdirSync(BRIDGE)
    .filter((f: string) => /^step-\\d+-impl\\.js$/.test(f))
    .sort();
  console.log(\`[stubs] Bridge dir: \${BRIDGE}\`);
  console.log(\`[stubs] Restored impls after cleanup: [\${survivingImpls.join(', ')}]\`);
  if (survivingImpls.length === 0) {
    console.log('[stubs] WARNING: No impl files found — all steps will pause for MCP analysis');
  }
  const launchManifest = readJsonIfExists(path.join(BRIDGE, 'launch.json'));
  atomicWriteJsonSync(path.join(BRIDGE, 'run.json'), {
      ...launchManifest,
      runId: RUN_ID,
      bridgeDir: BRIDGE,
      bridgeRoot: BRIDGE_ROOT,
      runtimeStartedAt: RUN_STARTED_AT,
      implAttemptTimeoutMs: IMPL_ATTEMPT_TIMEOUT_MS,
      runDeadlineAt: launchManifest.runDeadlineAt ?? RUN_DEADLINE_AT,
      runTimeoutMs: launchManifest.runTimeoutMs ?? RUN_TIMEOUT_MS,
      timeoutMs: launchManifest.timeoutMs ?? RUN_TIMEOUT_MS,
      runtimePid: process.pid,
  });
  atomicWriteJsonSync(path.join(BRIDGE, 'steps.json'), STEP_REGISTRY);
});

const stepOccurrences = new Map<string, number>();

function claimStepIndex(stepKey: string, indexes: number[]): number {
  const occurrence = stepOccurrences.get(stepKey) ?? 0;
  if (occurrence >= indexes.length) {
    throw new Error(
      \`Stub occurrence overflow for "\${stepKey}". Expected at most \${indexes.length} invocation(s).\`
    );
  }
  stepOccurrences.set(stepKey, occurrence + 1);
  return indexes[occurrence];
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function assertRunNotExpired(): void {
  if (Date.now() < RUN_DEADLINE_AT) return;
  throw new Error(
    \`run_timeout: attach run exceeded deadline \${new Date(RUN_DEADLINE_AT).toISOString()}\`
  );
}

async function withImplAttemptTimeout<T>(task: Promise<T>, stepIndex: number): Promise<T> {
  return await Promise.race([
    task,
    new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error(\`impl_attempt_timeout: step \${stepIndex} exceeded \${IMPL_ATTEMPT_TIMEOUT_MS}ms\`));
      }, IMPL_ATTEMPT_TIMEOUT_MS);
    }),
  ]) as Promise<T>;
}

/**
 * Core stub runner.
 *
 * Protocol (files in mcp-bridge/<runId>/):
 *   step-N-pause.json  — written by stub when waiting for implementation
 *   step-N-impl.js     — written by Claude (CommonJS, exports async function)
 *   step-N-pass.signal — written by stub on successful execution
 *   step-N-error.txt   — written by stub on failed execution (cleared on retry)
 */
async function runStub(
  world: ${worldType},
  n: number,
  stepText: string,
  args: unknown[],
): Promise<void> {
  const stepInfo = STEP_REGISTRY[n];
  const implFile  = path.join(BRIDGE, \`step-\${n}-impl.js\`);
  const pauseFile = path.join(BRIDGE, \`step-\${n}-pause.json\`);
  const passFile  = path.join(BRIDGE, \`step-\${n}-pass.signal\`);
  const passMetaFile = path.join(BRIDGE, \`step-\${n}-pass.json\`);
  const errorFile = path.join(BRIDGE, \`step-\${n}-error.txt\`);

  // Pause only when no impl exists yet (first attempt or after a failure wipe)
  if (!fs.existsSync(implFile)) {
    assertRunNotExpired();
    atomicWriteJsonSync(pauseFile, {
      runId: RUN_ID,
      bridgeDir: BRIDGE,
      bridgeRoot: BRIDGE_ROOT,
      runStartedAt: RUN_STARTED_AT,
      implAttemptTimeoutMs: IMPL_ATTEMPT_TIMEOUT_MS,
      runDeadlineAt: RUN_DEADLINE_AT,
      runTimeoutMs: RUN_TIMEOUT_MS,
      timeoutMs: RUN_TIMEOUT_MS,
      deadlineAt: RUN_DEADLINE_AT,
      stepIndex: n,
      step: stepText,
      type: stepInfo.type,
      stepKey: stepInfo.stepKey,
      occurrence: stepInfo.occurrence,
      occurrenceCount: stepInfo.occurrenceCount,
      url: ${pageUrlExpression} ?? '',
      args,
      timestamp: Date.now(),
    });
    while (!fs.existsSync(implFile)) {
      assertRunNotExpired();
      await sleep(500);
    }
  }

  // Execution loop — reloads impl on each iteration (allows live rewriting)
  while (true) {
    try {
      assertRunNotExpired();
      const implPath = path.resolve(implFile);
      // Clear require cache so rewritten files are picked up immediately
      delete (require as any).cache[implPath];
      const impl = require(implPath);
      await withImplAttemptTimeout((impl as Function).call(world, ...args), n);

      // Success
      atomicWriteFileSync(passFile, String(Date.now()));
      atomicWriteJsonSync(passMetaFile, {
        runId: RUN_ID,
        stepIndex: n,
        step: stepText,
        occurrence: stepInfo.occurrence,
        occurrenceCount: stepInfo.occurrenceCount,
        completedAt: Date.now(),
      });
      return;

    } catch (err: unknown) {
      const msg = err instanceof Error
        ? err.message + '\\n' + (err.stack ?? '')
        : String(err);

      atomicWriteFileSync(errorFile, msg);
      if (fs.existsSync(implFile)) fs.unlinkSync(implFile);

      // Wait for Claude to rewrite impl
      while (!fs.existsSync(implFile)) {
        assertRunNotExpired();
        await sleep(500);
      }

      // Clear error so next attempt starts clean
      if (fs.existsSync(errorFile)) fs.unlinkSync(errorFile);
    }
  }
}
`;

// ---------------------------------------------------------------------------
// Step bindings
// ---------------------------------------------------------------------------
const FN_MAP = { Given: 'Given', When: 'When', Then: 'Then' };
const groupedSteps = new Map();
const occurrenceCounts = new Map();

for (const step of steps) {
  const key = `${step.type}::${step.text}`;
  const entry = groupedSteps.get(key);
  if (entry) {
    entry.indexes.push(step.index);
  } else {
    groupedSteps.set(key, {
      type: step.type,
      text: step.text,
      indexes: [step.index],
    });
  }
  occurrenceCounts.set(key, (occurrenceCounts.get(key) ?? 0) + 1);
}

const stepRegistry = {};
const stepOccurrenceSeen = new Map();
for (const step of steps) {
  const stepKey = `${step.type}::${step.text}`;
  const occurrence = (stepOccurrenceSeen.get(stepKey) ?? 0) + 1;
  stepOccurrenceSeen.set(stepKey, occurrence);
  stepRegistry[step.index] = {
    index: step.index,
    type: step.type,
    text: step.text,
    stepKey,
    occurrence,
    occurrenceCount: occurrenceCounts.get(stepKey) ?? 1,
  };
}

const registrySource = `const STEP_REGISTRY: Record<number, {
  index: number;
  type: string;
  text: string;
  stepKey: string;
  occurrence: number;
  occurrenceCount: number;
}> = ${JSON.stringify(stepRegistry, null, 2)};\n`;

const bindings = Array.from(groupedSteps.values()).map(({ type, text, indexes }) => {
  const fn = FN_MAP[type] || 'When';
  const params = getParams(text);
  const escapedText = text.replace(/"/g, '\\"');
  const stepKey = `${type}::${text}`.replace(/"/g, '\\"');

  const paramDecl = params.length > 0
    ? ', ' + params.map(p => `${p.name}: ${p.tsType}`).join(', ')
    : '';

  const argsArray = params.length > 0
    ? `[${params.map(p => p.name).join(', ')}]`
    : '[]';

  const stepIndexExpr = indexes.length === 1
    ? `${indexes[0]}`
    : `claimStepIndex("${stepKey}", [${indexes.join(', ')}])`;

  return `${fn}("${escapedText}", async function (this: ${worldType}${paramDecl}) {
  await runStub(this, ${stepIndexExpr}, "${escapedText}", ${argsArray});
});`;
}).join('\n\n');

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------
const output = header + '\n' + registrySource + '\n' + bindings + '\n';

fs.mkdirSync(path.dirname(path.resolve(outputFile)), { recursive: true });
fs.writeFileSync(outputFile, output, 'utf8');
console.log(`Generated ${steps.length} stub(s) → ${outputFile}`);
